spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        path-style-access-enabled: ${AWS_S3_FORCE_PATH_STYLE:false}
        endpoint: ${AWS_S3_ENDPOINT:https://s3.amazonaws.com}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:https://sqs.us-east-1.amazonaws.com}

aws:
  region: ${AWS_REGION:us-east-1}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  forcePathStyle: ${AWS_S3_FORCE_PATH_STYLE:false}
  s3:
    bucket: ${AWS_S3_BUCKET}
  sqs:
    queue: ${AWS_SQS_QUEUE_NAME}

app:
  download-url: ${APP_DOWNLOAD_URL}