spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videos
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

aws:
  region: us-east-1
  accessKey: test
  secretKey: test
  endpoint: http://localhost:4566
  forcePathStyle: true
  s3:
    bucket: videos
  sqs:
    endpoint: http://localhost:4566
    queue: video-queue
  stack:
    auto: false

app:
  download-url: http://localhost:8080/controller/v1/download/