spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

aws:
  region: ${AWS_REGION:us-east-1}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  forcePathStyle: ${AWS_S3_FORCE_PATH_STYLE:false}
  s3:
    bucket: ${AWS_S3_BUCKET}
    endpoint: ${AWS_S3_ENDPOINT:http://s3.amazonaws.com}
  sqs:
    queue: ${AWS_SQS_QUEUE_NAME}
    endpoint: ${AWS_SQS_ENDPOINT:http://sqs.amazonaws.com}

app:
  download-url: ${APP_DOWNLOAD_URL}